### ISSUE TITLE
Automatically Search for DeliveryPackets and add them into the DeliveryVault

### ISSUE THREAD

**Issue by julianhelpertz** [AntiBotDeluxe/delivery#16]
The idea is that **delivery** is smart enough to scan the whole project on start-up and register all **Java Classes** which implement the Interface `DeliveryPacket` so the developer does not have to manually register them.

**Comment by julianhelpertz** [comment]
What do you this idea @madebyfusion and got any ideas for implementing this feature?

**Comment by madebyfusion** [comment]
> What do you this idea @madebyfusion and got any ideas for implementing this feature?

That should work through reflections, however I think having it run once at startup could lead to some issues. Java resources implementing with delivery should call a function to implement the packets. We can further discuss this in another meeting.
